"""empty message

Revision ID: a45a16dec048
Revises: 1e3a6bde180b
Create Date: 2024-10-03 02:45:49.150138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45a16dec048'
down_revision = '1e3a6bde180b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_to', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contents', schema=None) as batch_op:
        batch_op.drop_column('link_to')

    # ### end Alembic commands ###
